### ISSUE TITLE
Plugin Constants are Undefined

### ISSUE THREAD

**Issue by matthewborgman** [croxton/cat2#4]
Hi.

In the latest version of the plugin, PHP notices are being generated because it appears that the plugins constants are not defined in the right order. See attached screenshots.

![php_notices](https://cloud.githubusercontent.com/assets/574527/20281476/45d26902-aa76-11e6-8d1f-525af7e0d9c2.png)
![plugins](https://cloud.githubusercontent.com/assets/574527/20281480/49287b46-aa76-11e6-85ba-68cd8a527880.png)

**Comment by croxton** [comment]
Yeah sorry I cocked up the EE2 compatibility. Fixed in 2.0.1 so please download again.

**Comment by matthewborgman** [comment]
Thanks for the quick resolution, @croxton.
